name: Build Windows Shared

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:        
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install autopoint gcc-mingw-w64-x86-64 gettext g++-mingw-w64-x86-64 mingw-w64-tools yasm

      - name: Build
        run: |
          mkdir vlc-installed
          mkdir build
          cd build
          CONTRIBFLAGS="--disable-amf --disable-aom --disable-aribb24 --disable-aribb25 --disable-asdcplib --disable-basu --disable-bluray --disable-bpg --disable-breakpad --disable-caca \
          --disable-cargo-c --disable-chromaprint --disable-daala --disable-dav1d --disable-decklink --disable-dvbcsa --disable-dvbpsi --disable-dvdcss --disable-dvdnav --disable-dvdread \
          --disable-ebml --disable-ffi --disable-flac --disable-fluid --disable-fluidlite" \
          ../extras/package/win32/build.sh -a x86_64 -z -o ${{ github.workspace }}/vlc-installed/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VLC-Win64-Shared
          path: ${{ github.workspace }}/vlc-installed
          if-no-files-found: ignore
          retention-days: 0
